---
server:
  port: 8761
spring:
  profiles: 192.168.31.111
  application:
    name: eureka-ha

eureka:
  instance:
    preferIpAddress: true
    hostname: 192.168.31.111
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://192.168.31.215:8761/eureka/

---
server:
  port: 8761
spring:
  profiles: 192.168.31.215
  application:
    name: eureka-ha

eureka:
  instance:
    preferIpAddress: true
    hostname: 192.168.31.215
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://192.168.31.111:8761/eureka/
