---
server:
  port: 8761
spring:
  profiles: 192.168.31.111
  application:
    name: eureka-ha

eureka:
  server:
    enable-self-preservation: false # 退出保护模式（生产环境上不推荐）
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: 192.168.31.111
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://192.168.31.215:8761/eureka/

---
server:
  port: 8761
spring:
  profiles: 192.168.31.215
  application:
    name: eureka-ha

eureka:
  server:
    enable-self-preservation: false # 退出保护模式（生产环境上不推荐）
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: 192.168.31.215
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://192.168.31.111:8761/eureka/
