server:
  port: 9001
spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      #      defaultZone: http://edward:1234@localhost:8761/eureka/
      defaultZone: http://edward:1234@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
