server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://edward:1234@localhost:8761/eureka/
#spring:
#  security:
#    user:
#      name: edward
#      password: 1234
